---
language: python
python: 2.7
cache: pip
sudo: required

services:
  - docker

matrix:
  fast_finish: true

env:
  - TEST_RUN="./tests/test-kubeadm-dind-cluster.sh"
  - TEST_RUN="./tests/test-kubernetes.sh"

before_install:
  - sudo apt-get install shellcheck
  - pip install -U -r test-requirements.txt

install:
  - "./scripts/install.sh"
  - "./scripts/bx_auth.sh"

before_script:
  - "./tests/test-shellcheck.sh"
  - "./tests/test-yamllint.sh"

script: "$TEST_RUN"
